---
name: Cache Cleanup

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 2 * * 0"
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  cleanup-caches:
    uses: miikkak/workflows/.github/workflows/cache-cleanup.yml@e13cfbf2b04c2c0f3140a88bb26ac0947ac373e5 # main
    secrets: inherit
