---
name: Post-Merge Pipeline

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  cd:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    uses: miikkak/workflows/.github/workflows/cd.yml@bc94533be449cb1f5d0976594d431dc11386b158 # main
    secrets:
      SEMANTIC_RELEASE_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
    with:
      code-paths: >-
        '**/*.java', '**/*.kts', 'gradle.properties', 'gradle/wrapper/**',
        '.github/workflows/**', '.pre-commit-config.yaml', '.releaserc.json'
