---
name: Post-Merge Pipeline

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  cd:
    uses: miikkak/workflows/.github/workflows/cd.yml@61e21a8c9df09a3a951c620ed5e8acd63ebc1e3d # main
    secrets:
      SEMANTIC_RELEASE_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
    with:
      code-paths: >-
        '**/*.java', '**/*.kts', 'gradle.properties', 'gradle/wrapper/**',
        '.github/workflows/**', '.pre-commit-config.yaml', '.releaserc.json'
