---
name: PR Validation

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: read

jobs:
  ci-cd:
    uses: miikkak/workflows/.github/workflows/ci-cd.yml@b2fba38516c51472610b61160ddaee133eb6c068 # main
    with:
      code-paths: >-
        '**/*.java', '**/*.kts', 'gradle.properties', 'gradle/wrapper/**',
        '.github/workflows/**', '.pre-commit-config.yaml', '.releaserc.json'
