---
name: PR Validation

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  ci-cd:
    uses: miikkak/workflows/.github/workflows/ci-cd.yml@b43a69f8bd367f9beb0dfd8d84b93294d27c387b # main
    with:
      code-paths: >-
        '**/*.java', '**/*.kts', 'gradle.properties', 'gradle/wrapper/**',
        '.github/workflows/**', '.pre-commit-config.yaml', '.releaserc.json'
