---
name: Code Review

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, ready_for_review, synchronize]
    branches: [main]

permissions:
  contents: read
  pull-requests: write

  actions: write
jobs:
  review:
    if: github.event.pull_request.draft == false
    uses: miikkak/workflows/.github/workflows/code-review.yml@b7caf5aec23f15dff5ea2df3d2fe9394da99c404 # main
    with:
      enabled: true
    secrets: inherit
