---
name: Code Review

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, ready_for_review, synchronize]
    branches: [main]

permissions:
  contents: read
  pull-requests: write

  actions: write
jobs:
  review:
    if: github.event.pull_request.draft == false
    uses: miikkak/workflows/.github/workflows/code-review.yml@e13cfbf2b04c2c0f3140a88bb26ac0947ac373e5 # main
    with:
      enabled: true
    secrets: inherit
