---
name: Dependabot Automerge

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    name: Dependabot Automerge
    uses: miikkak/workflows/.github/workflows/dependabot-automerge.yml@eea944d066babc3d282b1deb160c583e7f0a0509 # main
    secrets:
      PULL_REQUEST_TOKEN: ${{ secrets.PULL_REQUEST_TOKEN }}
