---
name: Dependabot Automerge

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    name: Dependabot Automerge
    uses: miikkak/workflows/.github/workflows/dependabot-automerge.yml@20a0b39f9560f0f086d462a53948fdb5a753ea2c # main
    secrets:
      PULL_REQUEST_TOKEN: ${{ secrets.PULL_REQUEST_TOKEN }}
