---
name: Gradle Lockfile Refresh

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  refresh-lockfile:
    name: Gradle Lockfile Refresh
    uses: miikkak/workflows/.github/workflows/gradle-lockfile-refresh.yml@20a0b39f9560f0f086d462a53948fdb5a753ea2c # main
    secrets:
      PULL_REQUEST_TOKEN: ${{ secrets.PULL_REQUEST_TOKEN }}
