---
name: Gradle Lockfile Refresh

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  refresh-lockfile:
    name: Gradle Lockfile Refresh
    uses: miikkak/workflows/.github/workflows/gradle-lockfile-refresh.yml@e1f058b6743c6d2302359c4b8f335a0da0e3799d # main
    secrets:
      PULL_REQUEST_TOKEN: ${{ secrets.PULL_REQUEST_TOKEN }}
