---
name: Gradle Lockfile Refresh

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  refresh-lockfile:
    name: Gradle Lockfile Refresh
    uses: miikkak/workflows/.github/workflows/gradle-lockfile-refresh.yml@08d8570d1d247aa5625e3b156f21a3566da108ab # main
    secrets:
      PULL_REQUEST_TOKEN: ${{ secrets.PULL_REQUEST_TOKEN }}
