---
name: PR Check

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

permissions:
  contents: read
  actions: write

jobs:
  pre-commit:
    uses: miikkak/workflows/.github/workflows/pr-check.yml@faf5151059633043890902d27d52ccfbef45d479 # main
    secrets: inherit
