---
name: Pre-commit Hook Updates

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "30 9 * * 1"
  workflow_dispatch:


permissions:
  contents: write
  issues: write
  pull-requests: write

  actions: write
jobs:
  check-updates:
    uses: miikkak/workflows/.github/workflows/precommit-updates.yml@e599eb3588fa60cd265bdb678509a3e61a7f3abe # main
    secrets: inherit
