---
name: Pre-commit Hook Updates

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "30 9 * * 1"
  workflow_dispatch:


permissions:
  contents: write
  issues: write
  pull-requests: write

  actions: write
jobs:
  check-updates:
    uses: miikkak/workflows/.github/workflows/precommit-updates.yml@d53fdc93aebbce5e4c300ca223247e5703ebe7dd # main
    secrets: inherit
