---
name: Pre-commit Hook Updates

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "30 9 * * 1"
  workflow_dispatch:


permissions:
  contents: write
  issues: write
  pull-requests: write

  actions: write
jobs:
  check-updates:
    uses: miikkak/workflows/.github/workflows/precommit-updates.yml@cfc6f1b2d8384e309c63ea1f721402779eb6436c # main
    secrets: inherit
