---
name: Release Label

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  pull-requests: read

jobs:
  release-label:
    name: Release Label Check
    uses: miikkak/workflows/.github/workflows/check-release-label.yml@c06d611d08a0a3accc3447508ce6dd6ba447c289 # main
    permissions:
      contents: read
      pull-requests: read
