---
name: Secret Scan

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
  push:
    branches: ["**"]
  schedule:
    # Run daily at 03:30 UTC
    - cron: "30 3 * * *"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  secret-scan:
    uses: miikkak/workflows/.github/workflows/secret-scan.yml@32aa77c50dd670ab1be4adb0cd668c2dac79575c # main
