---
name: Secret Scan

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
  push:
    branches: ["**"]
  schedule:
    # Run daily at 03:30 UTC
    - cron: "30 3 * * *"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  secret-scan:
    uses: miikkak/workflows/.github/workflows/secret-scan.yml@7f2d4cedeb7fa96d740de1f5c128916700b0b85f # main
