---
name: Scheduled Security Scan

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  security:
    uses: miikkak/workflows/.github/workflows/security-scan.yml@a12d676d882832ddbbab070f3b58405c3c122d34 # main
    secrets: inherit
