---
name: Lint

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
  workflow_dispatch:


permissions:
  contents: read
  statuses: write

jobs:
  super-lint:
    uses: miikkak/workflows/.github/workflows/super-linter.yml@9c41649397e948b55efc6c7f67441faba4b620af # main
    secrets: inherit
    with:
      validate-bash: false
      validate-json: true
