---
name: Lint

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
  workflow_dispatch:


permissions:
  contents: read
  statuses: write

jobs:
  super-lint:
    uses: miikkak/workflows/.github/workflows/super-linter.yml@c06d611d08a0a3accc3447508ce6dd6ba447c289 # main
    secrets: inherit
    with:
      validate-bash: false
      validate-json: true
