---
name: Lint

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
  workflow_dispatch:


permissions:
  contents: read
  statuses: write

jobs:
  super-lint:
    uses: miikkak/workflows/.github/workflows/super-linter.yml@5ed974520d8d956690f6e6ed1ad09e34440fa100 # main
    secrets: inherit
    with:
      validate-bash: false
      validate-json: true
